### ISSUE TITLE
compile error..

### ISSUE THREAD

**Issue by Thanh-Binh** [vichargrave/wqueue#1]
I try to test it but there is a compile error like:
g++ -c -Wall -I../threads main.cpp -o main.o
g++ -c -Wall -I../threads ../threads/thread.cpp -o ../threads/thread.o
g++ -lpthread main.o ../threads/thread.o -o wqueue
../threads/thread.o: In function `Thread::~Thread()':
thread.cpp:(.text+0x9b): undefined reference to `pthread_detach'
thread.cpp:(.text+0xb7): undefined reference to `pthread_cancel'
../threads/thread.o: In function `Thread::start()':
thread.cpp:(.text+0x11e): undefined reference to `pthread_create'
../threads/thread.o: In function `Thread::join()':
thread.cpp:(.text+0x16c): undefined reference to `pthread_join'
../threads/thread.o: In function `Thread::detach()':
thread.cpp:(.text+0x1c0): undefined reference to `pthread_detach'
collect2: error: ld returned 1 exit status
Makefile:12: recipe for target 'wqueue' failed
make: *** [wqueue] Error 1

Moreover, I want to get results back to the main().
How can I do it?
Best thanks for you help.

**Comment by vichargrave** [comment]
Sorry for the pate reply.  It appears that pthreads is not installed on your platform.  Install it then try again.

**Comment by Thanh-Binh** [comment]
OK. thanks
